name: Verify frontend

on:
  pull_request:
    path:
      - .github/workflows/verify-pr.yaml
      - devconnect-front-end/**

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  verify-frontend:
    name: Verify frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd devconnect-front-end
          npm install

      - name: Lint code
        run: |
          cd devconnect-front-end
          npm run lint

      - name: Build project
        run: |
          cd devconnect-front-end
          npm run build
